const Map<String, String> _areaFlags = {
  'American': '🇺🇸',
  'British': '🇬🇧',
  'Canadian': '🇨🇦',
  'Chinese': '🇨🇳',
  'Croatian': '🇭🇷',
  'Dutch': '🇳🇱',
  'Egyptian': '🇪🇬',
  'Filipino': '🇵🇭',
  'French': '🇫🇷',
  'Greek': '🇬🇷',
  'Indian': '🇮🇳',
  'Irish': '🇮🇪',
  'Italian': '🇮🇹',
  'Jamaican': '🇯🇲',
  'Japanese': '🇯🇵',
  'Kenyan': '🇰🇪',
  'Malaysian': '🇲🇾',
  'Mexican': '🇲🇽',
  'Moroccan': '🇲🇦',
  'Polish': '🇵🇱',
  'Portuguese': '🇵🇹',
  'Russian': '🇷🇺',
  'Spanish': '🇪🇸',
  'Thai': '🇹🇭',
  'Tunisian': '🇹🇳',
  'Turkish': '🇹🇷',
  'Ukrainian': '🇺🇦',
  'Uruguayan': '🇺🇾',
  'Vietnamese': '🇻🇳',
  'Australian': '🇦🇺',
  'Bangladeshi': '🇧🇩',
  'Burmese': '🇲🇲',
  'Brazilian': '🇧🇷',
  'Peruvian': '🇵🇪',
  'Korean': '🇰🇷',
  'Taiwanese': '🇹🇼',
};

String flagForArea(String area) => _areaFlags[area] ?? '🌍';
